# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0003_auto_20171012_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewall',
            name='firewall_active',
        ),
    ]
