# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0004_remove_firewall_firewall_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_application', models.CharField(max_length=10, verbose_name='Application')),
            ],
        ),
        migrations.CreateModel(
            name='Destination_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_destination_address', models.CharField(max_length=10, verbose_name='Destination Address')),
            ],
        ),
        migrations.CreateModel(
            name='Source_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_source_address', models.CharField(max_length=10, verbose_name='Source Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='firewall',
            name='firewall_policies',
        ),
        migrations.AddField(
            model_name='firewall',
            name='firewall_policies',
            field=models.ManyToManyField(to='policy_mgmnt.Policies'),
        ),
        migrations.RemoveField(
            model_name='policies',
            name='policy_application',
        ),
        migrations.RemoveField(
            model_name='policies',
            name='policy_destination_address',
        ),
        migrations.RemoveField(
            model_name='policies',
            name='policy_source_address',
        ),
        migrations.AddField(
            model_name='policies',
            name='policy_application',
            field=models.ManyToManyField(to='policy_mgmnt.Application'),
        ),
        migrations.AddField(
            model_name='policies',
            name='policy_destination_address',
            field=models.ManyToManyField(to='policy_mgmnt.Destination_Address'),
        ),
        migrations.AddField(
            model_name='policies',
            name='policy_source_address',
            field=models.ManyToManyField(to='policy_mgmnt.Source_Address'),
        ),
    ]
