# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0008_auto_20171016_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policies',
            old_name='id',
            new_name='ID',
        ),
    ]
