# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0009_auto_20171016_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policies',
            old_name='ID',
            new_name='id',
        ),
    ]
