# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0010_auto_20171016_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='policies',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
