# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0011_auto_20171017_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='policies',
            name='annotation',
            field=models.CharField(blank=True, default=1, max_length=10, verbose_name='Annotation'),
        ),
        migrations.RemoveField(
            model_name='policies',
            name='application',
        ),
        migrations.AddField(
            model_name='policies',
            name='application',
            field=models.CharField(default=1, max_length=10, verbose_name='Application'),
        ),
        migrations.RemoveField(
            model_name='policies',
            name='destination_address',
        ),
        migrations.AddField(
            model_name='policies',
            name='destination_address',
            field=models.CharField(default=1, max_length=10, verbose_name='Destination_Address'),
        ),
        migrations.AlterField(
            model_name='policies',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='policies',
            name='source_address',
        ),
        migrations.AddField(
            model_name='policies',
            name='source_address',
            field=models.CharField(default=1, max_length=10, verbose_name='Source_Address'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Destination_Address',
        ),
        migrations.DeleteModel(
            name='Source_Address',
        ),
    ]
