# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0012_auto_20171017_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_info', models.CharField(max_length=50, verbose_name='source')),
                ('dest_info', models.CharField(max_length=50, verbose_name='dest')),
                ('app_info', models.CharField(max_length=50, verbose_name='app')),
            ],
        ),
    ]
