# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0013_input'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input',
            new_name='POST',
        ),
    ]
