# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0015_auto_20171023_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='POST_POLICY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_info', models.CharField(max_length=50, verbose_name='policy_name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='firewall',
            options={'ordering': ['-firewall_name']},
        ),
    ]
