# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0017_auto_20171024_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='POST_POL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_info', models.CharField(max_length=50, verbose_name='source')),
                ('dest_info', models.CharField(max_length=50, verbose_name='dest')),
                ('app_info', models.CharField(max_length=50, verbose_name='app')),
            ],
        ),
    ]
