# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0023_auto_20180108_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='source_ip',
            field=models.CharField(default=1, max_length=10, verbose_name='Source_IP'),
        ),
    ]
