# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0024_policies_source_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policies',
            name='dst_zone',
        ),
        migrations.RemoveField(
            model_name='policies',
            name='src_zone',
        ),
    ]
