# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-17 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0025_auto_20180111_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policies',
            name='source_ip',
        ),
    ]
