# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0031_auto_20180119_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='dst_address_set',
            field=models.CharField(default=1, max_length=10, verbose_name='Address_Set'),
        ),
    ]
