# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0032_policies_dst_address_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='dest_defined_as',
            field=models.CharField(default=1, max_length=10, verbose_name='Defined_As'),
        ),
    ]
