# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_mgmnt', '0034_policies_source_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='dest_ip',
            field=models.CharField(default=1, max_length=10, verbose_name='Destination_Address'),
        ),
    ]
